language: java

notifications:
  email:
    recipients:
      - ghazni.nattarshah@gmail.com
      - mahendran.rajagopal@objectfrontier.com
    on_success: always
    on_failure: always
    
cache:
  directories:
    - dist